name: Sync Fork

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v2.0.10
        with:
          owner: 
          repo: 
          base: main                      # 上游仓库的基础分支
          head: main                      # 你的 fork 仓库的头部分支
          token: ${{ secrets.PERSONAL_TOKEN }} # 必须使用具有 repo/public_repo 权限的 PAT

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 2
